name       : kipi-plugins
version    : 20.04.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kipi-plugins-20.04.0.tar.xz : b6ebb6d3081b8281b4e6e13445347258b53f88ef3b61e0f39e71635d20983547
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
