name       : kipi-plugins
version    : 19.12.1
release    : 8
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kipi-plugins-19.12.1.tar.xz : bcd27ab29b491f13116a156e403126d04ffbaa352b581eca7fb0904e13c5dabe
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
