name       : kipi-plugins
version    : 21.04.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kipi-plugins-21.04.1.tar.xz : af4c744ab4e13922827745212ad34c1ea113c33a9c68911452dec1593a4ce74e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - karchive-devel
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
