name       : kipi-plugins
version    : 21.12.1
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kipi-plugins-21.12.1.tar.xz : 70babcd4c4b16ab6111d9787750dc48018751eb17bc0813557f486d6d0cb4db5
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
