name       : kipi-plugins
version    : 21.12.3
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kipi-plugins-21.12.3.tar.xz : fe471526e7c63924c6a30b647e2440a5f237bd782ca4d0b4f44c1a25da01c1c0
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
