name       : kipi-plugins
version    : 20.04.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kipi-plugins-20.04.3.tar.xz : e128ba8a2194bb0ce6a5eac97d56479003f08c1d740a56a6c8d976df1a71632a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
