name       : kipi-plugins
version    : 20.12.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kipi-plugins-20.12.2.tar.xz : 880ad1541cbe786da960510e16b618505c779e7b44a3c39019e46cece6891e88
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - karchive-devel
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
