name       : kipi-plugins
version    : 20.12.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kipi-plugins-20.12.0.tar.xz : 54bac3f5beffd4034cbc12ca8c7fbf6816f921be1db39e64a081b9c4f271878e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
