name       : kipi-plugins
version    : 19.08.2
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kipi-plugins-19.08.2.tar.xz : 2894f50989a14f7fd4be0035efec3cb14583d2285ff11729605b641af0fed192
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
