name       : kipi-plugins
version    : 20.08.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kipi-plugins-20.08.2.tar.xz : 89de8f75dd01e2130c1e651bd04717ce4d35768202ae3e825c93c75c8312e583
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
