name       : kipi-plugins
version    : 21.04.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kipi-plugins-21.04.2.tar.xz : a510f13809f5307c3d5ffc979c1aa6f9dfbe24112e2f613178b3f02249850991
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - karchive-devel
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
