name       : kipi-plugins
version    : 20.04.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kipi-plugins-20.04.1.tar.xz : 49f969d9078b3395ff307f499e1e17a04e46efb3461822795649b972432bec0a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
