name       : kipi-plugins
version    : 19.12.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kipi-plugins-19.12.3.tar.xz : 16997bd6fbb59c194c2997732c870e33bbacd3d7346546af9a255db3330ec5ac
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
