name       : kipi-plugins
version    : 19.12.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kipi-plugins-19.12.2.tar.xz : f7e835e9e282d67bfd6aabe9f8d9482da42ee686b6d27aa736fd212cf21ce1ac
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
