name       : kipi-plugins
version    : 19.12.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kipi-plugins-19.12.0.tar.xz : aa7c490a938768f2b54109cef8b9546d972035d403b3faf34b9abe3705946a12
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
