name       : kipi-plugins
version    : 21.08.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kipi-plugins-21.08.1.tar.xz : 2d5e023886f36f72fe00c3be1fc73aa886a7ef791e5c6cb62c415a60f9e0daf0
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
