name       : kipi-plugins
version    : 20.12.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kipi-plugins-20.12.1.tar.xz : 2dbd859e39190f2fc13442d1966a0d137b2f572987ab4d7edee5d833b671655f
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
