name       : kipi-plugins
version    : 20.12.3
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kipi-plugins-20.12.3.tar.xz : 16be32705e6056de9350d3713ab6b20659a236db1356eb32cd6cdd19ac71c071
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - karchive-devel
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
