name       : kipi-plugins
version    : 21.08.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kipi-plugins-21.08.0.tar.xz : 6fdb86bfb2ae1d13a1aa5a779cebfcec2c6331f43e2624b57282f69eba06d675
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
