name       : kipi-plugins
version    : 20.04.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kipi-plugins-20.04.2.tar.xz : 73e8b7d8ca28dc630a7112065eda8757a7ac47d5417b86b75c309c3382f06748
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
