name       : kipi-plugins
version    : 21.08.2
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kipi-plugins-21.08.2.tar.xz : b7efb1a9dba130f736a7e8850edb2e748ac0d7568196429cb1fe2f535b88f279
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A collection of plugins extending the KDE graphics and image applications
description: |
    A collection of plugins extending the KDE graphics and image applications
replaces   :
    - digikam-kipi-plugins
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
    - libkipi-devel
    - libkvkontakte-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
